#!/usr/bin/env bash
#
# Scripts in this directory are run during the build process.
# each script will be uploaded to /tmp on your build droplet,
# given execute permissions and run.  The cleanup process will
# remove the scripts from your build system after they have run
# if you use the build_image task.
#
echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends && \
    echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends && \
    apt-get -q update && \
    apt-get -q install locales && \
    locale-gen en_US.UTF-8 && \
    apt-get -q dist-upgrade -y

wget https://www.zulip.org/dist/releases/zulip-server-latest.tar.gz
tar -xf zulip-server-latest.tar.gz
wget https://gist.githubusercontent.com/hackerkid/d41fcace8db1da9eae04d42d13f19fbb/raw/e98c0c83369d0c57fdcd8bfd5a55ef30b5350430/install -O zulip-server-2.0.4/scripts/lib/install

array=(./zulip-server-*)
"${array[0]}"/scripts/setup/install --email=mail@example.com --hostname "$(hostname -f)" --no-init-db --self-signed-cert

rm -f /etc/zulip/zulip-secrets.conf /etc/zulip/settings.py

# Remove unnessary messages set by Ubuntu that appears during user login.
 rm /etc/update-motd.d/00-header
 rm /etc/update-motd.d/10-help-text
 rm /etc/update-motd.d/51-cloudguest
